// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqrtflvnhxbrwzshiatb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcnRmbHZuaHhicnd6c2hpYXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjY2MDgsImV4cCI6MjA3MDUwMjYwOH0.05CA6FGgvxBhxNPPrzQ96aVCbrmsLwQXNdz8jCYmIPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});